version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      npm-patch-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
      npm-minor-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      github-actions-patch-minor-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
