version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      npm-patch-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      github-actions-patch-minor-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
