name: Secret Scan (TruffleHog)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  trufflehog_pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Scan
        uses: trufflesecurity/trufflehog@v3.96.0
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified
          version: "3.96.0"

  trufflehog_push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Scan
        uses: trufflesecurity/trufflehog@v3.96.0
        with:
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified
          version: "3.96.0"
